export const dexPairs = [
  {
    chainId: "ethereum",
    dexId: "sushiswap",
    url: "https://dexscreener.com/ethereum/0xpair-low",
    pairAddress: "0xpair-low",
    labels: ["v2"],
    baseToken: { address: "0xAbC", name: "Alpha Token", symbol: "ALP" },
    quoteToken: { address: "0xUsdc", name: "USD Coin", symbol: "USDC" },
    priceNative: "0.0005",
    priceUsd: "1.25",
    txns: {
      m5: { buys: 2, sells: 1 },
      h1: { buys: 12, sells: 8 },
      h6: { buys: 55, sells: 40 },
      h24: { buys: 210, sells: 170 },
    },
    volume: { m5: 100, h1: 1_000, h6: 5_000, h24: 12_000 },
    priceChange: { m5: "0.1", h1: "1.2", h6: "-2.3", h24: "4.5" },
    liquidity: { usd: "12000", base: "4800", quote: "6000" },
    fdv: 1_250_000,
    marketCap: 1_000_000,
    pairCreatedAt: 1_700_000_000_000,
  },
  {
    chainId: "ethereum",
    dexId: "uniswap",
    url: "https://dexscreener.com/ethereum/0xpair-primary",
    pairAddress: "0xpair-primary",
    labels: ["v3"],
    baseToken: { address: "0xAbC", name: "Alpha Token", symbol: "ALP" },
    quoteToken: { address: "0xWeth", name: "Wrapped Ether", symbol: "WETH" },
    priceNative: "0.00051",
    priceUsd: "1.275",
    txns: {
      m5: { buys: 5, sells: 3 },
      h1: { buys: 35, sells: 20 },
      h6: { buys: 140, sells: 100 },
      h24: { buys: 600, sells: 410 },
    },
    volume: { m5: "850", h1: "7500", h6: "42000", h24: "125000" },
    priceChange: { m5: "0.4", h1: "2.1", h6: "3.7", h24: "8.2" },
    liquidity: { usd: "250000.50", base: "98039.41", quote: "50" },
    fdv: "1275000",
    marketCap: "1020000",
    pairCreatedAt: 1_710_000_000_000,
  },
  {
    chainId: "ethereum",
    dexId: "unknown-dex",
    url: "https://dexscreener.com/ethereum/0xpair-unknown-liquidity",
    pairAddress: "0xpair-unknown-liquidity",
    baseToken: { address: "0xAbC", name: "Alpha Token", symbol: "ALP" },
    quoteToken: { address: "0xQuote", name: "Quote Token", symbol: "QUOTE" },
    priceNative: "",
    priceUsd: null,
    txns: {},
    volume: {},
    priceChange: {},
    liquidity: { usd: "unknown", base: "", quote: null },
    fdv: null,
    marketCap: "",
    pairCreatedAt: null,
  },
];

export const dexPairsWithoutUsableLiquidity = [
  {
    ...dexPairs[2],
    pairAddress: "0xpair-no-liquidity",
    url: "https://dexscreener.com/ethereum/0xpair-no-liquidity",
  },
];

export const geckoPools = {
  data: [
    {
      id: "eth_0xpool-small",
      type: "pool",
      attributes: {
        address: "0xpool-small",
        name: "ALP / USDC",
        base_token_price_usd: "1.26",
        base_token_price_native_currency: "0.000504",
        quote_token_price_usd: "1",
        reserve_in_usd: "20000",
        volume_usd: { m5: "40", h1: "400", h6: "2400", h24: "9600" },
        price_change_percentage: { m5: "0.1", h1: "0.5", h6: "1.5", h24: "3" },
        transactions: {
          m5: { buys: 1, sells: 1, buyers: 1, sellers: 1 },
          h1: { buys: 5, sells: 4, buyers: 4, sellers: 4 },
        },
        fdv_usd: "1260000",
        market_cap_usd: "1008000",
        pool_created_at: "2024-01-01T00:00:00Z",
      },
      relationships: {
        base_token: { data: { id: "eth_0xabc", type: "token" } },
        quote_token: { data: { id: "eth_0xusdc", type: "token" } },
        dex: { data: { id: "sushiswap", type: "dex" } },
      },
    },
    {
      id: "eth_0xpool-primary",
      type: "pool",
      attributes: {
        address: "0xpool-primary",
        name: "ALP / WETH",
        base_token_price_usd: "1.27",
        base_token_price_native_currency: "0.000508",
        quote_token_price_usd: "2500",
        reserve_in_usd: "90000",
        volume_usd: { m5: "120", h1: "1200", h6: "7200", h24: "28800" },
        price_change_percentage: { m5: "0.2", h1: "0.8", h6: "2.4", h24: "4.8" },
        transactions: {
          m5: { buys: 3, sells: 2, buyers: 3, sellers: 2 },
          h1: { buys: 18, sells: 12, buyers: 15, sellers: 10 },
        },
        fdv_usd: "1270000",
        market_cap_usd: "1016000",
        pool_created_at: "2024-02-01T00:00:00Z",
      },
      relationships: {
        base_token: { data: { id: "eth_0xabc", type: "token" } },
        quote_token: { data: { id: "eth_0xweth", type: "token" } },
        dex: { data: { id: "uniswap-v3", type: "dex" } },
      },
    },
  ],
  included: [
    {
      id: "eth_0xabc",
      type: "token",
      attributes: { address: "0xAbC", name: "Alpha Token", symbol: "ALP" },
    },
    {
      id: "eth_0xusdc",
      type: "token",
      attributes: { address: "0xUsdc", name: "USD Coin", symbol: "USDC" },
    },
    {
      id: "eth_0xweth",
      type: "token",
      attributes: { address: "0xWeth", name: "Wrapped Ether", symbol: "WETH" },
    },
    { id: "sushiswap", type: "dex", attributes: { name: "SushiSwap" } },
    { id: "uniswap-v3", type: "dex", attributes: { name: "Uniswap V3" } },
  ],
};

export const goPlusToken = {
  code: 1,
  message: "OK",
  result: {
    "0xAbC": {
      token_name: "Alpha Token",
      token_symbol: "ALP",
      total_supply: "1000000",
      is_open_source: "1",
      is_proxy: "0",
      is_mintable: "",
      can_take_back_ownership: "0",
      owner_change_balance: "unknown",
      hidden_owner: null,
      selfdestruct: "0",
      external_call: "1",
      gas_abuse: " FALSE ",
      buy_tax: "0.035",
      sell_tax: "",
      cannot_buy: "0",
      cannot_sell_all: "1",
      slippage_modifiable: "1",
      personal_slippage_modifiable: "unknown",
      transfer_pausable: "",
      trading_cooldown: "0",
      is_honeypot: "0",
      is_blacklisted: "1",
      anti_whale: "1",
      anti_whale_modifiable: "0",
      holder_count: "187",
      holders: [
        {
          address: "0xholder1",
          tag: "creator",
          is_contract: "0",
          balance: "250000",
          percent: "0.25",
          is_locked: "0",
        },
        {
          address: "0xholder2",
          tag: "",
          is_contract: "1",
          balance: "170000",
          percent: "0.17",
          is_locked: "unknown",
        },
      ],
      lp_holder_count: "2",
      lp_holders: [
        {
          address: "0xlp1",
          tag: "locker",
          is_contract: "1",
          balance: "900",
          percent: "0.90",
          is_locked: "1",
        },
        {
          address: "0xlp2",
          tag: "",
          is_contract: "0",
          balance: "100",
          percent: "0.10",
          is_locked: "",
        },
      ],
      owner_address: "0xowner",
      owner_balance: "12345678901234567890.123",
      owner_percent: "0.125",
      creator_address: "0xcreator",
      creator_balance: "",
      creator_percent: "",
    },
  },
};
